site_name: Cetus Academy
extra_css:
    - style.css

# the documentation is written in polish
theme:
    name: material
    language: pl
    # codeblock highlighting
    highlightjs: true
    hljs_languages:
        - js
        - ts
        - json

#
markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
    - toc:
          permalink: true
    - pymdownx.superfences

# files in docs are structured in english, but they must be shown in polish, which is why they are instead defined in this index
nav:
    - "index.md"
    - "trash.md"
    - "available-books.md"
    - JavaScript:
          - "trash.md"
    - .NET:
          - "trash.md"
    - React.JS:
          - Starter Kit:
                - "reactjs/roadmap.md"
                - "reactjs/courses.md"
                - "reactjs/what-to-know.md"
          - "reactjs/style-guide.md"
          - "reactjs/working-with-different-resolutions.md"
          - "reactjs/saving-private-keys.md"
    - React Native:
          - "trash.md"
    - NestJS:
          - "trash.md"
    - Praca z Git:
          - "trash.md"
    - Praca w projekcie:
          - "trash.md"
    - Przydane poradniki wideo:
          - "trash.md"
