site_name: Baza wiedzy Cetus Academy
plugins:
    - mkdocs-video
    - search

theme:
    name: material
    language: pl
    # codeblock highlighting
    highlightjs: true
    hljs_languages:
        - js
        - ts
        - json
    logo: asset/logo-dark.png
    palette:
        primary: white

extra_css:
    - asset/style.css

# extras for codeblock highlighting
markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
    - toc:
          permalink: true
    - pymdownx.superfences

# files in docs are structured in english, but they must be shown in polish, which is why they are instead defined in this index
nav:
    - "index.md"
    - "trash.md"
    - "available-books.md"
    - JavaScript:
          - "javascript/good-practices-and-common-mistakes.md"
          - "javascript/style-guide.md"
    - .NET:
          - "dotnet/introduction.md"
    - React.JS:
          - Starter Kit:
                - "reactjs/roadmap.md"
                - "reactjs/courses.md"
                - "reactjs/what-to-know.md"
          - "reactjs/working-with-different-resolutions.md"
          - "reactjs/saving-private-keys.md"
    - NestJS:
          - "nestjs/general-naming-conventions.md"
          - "nestjs/file-types-and-their-purpose.md"
          - "nestjs/folders-and-their-role.md"
          - "nestjs/using-entity.md"
          - "nestjs/authentication-in-nestjs.md"
    - Praca z Git:
          - "working-with-git/working-with-git.md"
          - "working-with-git/working-with-a-new-exercise.md"
          - "working-with-git/checklist-of-a-new-pull-request.md"
    - Przydane poradniki wideo:
          - "video-tutorials/how-to-check-the-css-of-an-element-on-a-webpage.md"
