name: Publish docs via GitHub Pages

on:
    push:
        branches: [main]

jobs:
    build:
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: "pypy-3.7"

            - name: Workaround requirements.txt
              run: echo "" > /home/runner/work/_actions/afritzler/mkdocs-gh-pages-action/main/requirements.txt

            - name: Deploy docs
              uses: afritzler/mkdocs-gh-pages-action@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REQUIREMENTS: requirements.txt
                  #GITHUB_DOMAIN: github.myenterprise.com
